config/routes.rb
Rails.application.routes.draw do
  
  root to: 'posts#index'

  devise_for :users
  
  resources :posts, except: :index do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :favorites
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :user
  has_many :likes, dependent: :destroy #投稿が消えたらお気に入りも消える
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy #ユーザーがデータベースから削除されてしまった場合にユーザーがした投稿も全て消える
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  # フォローしようとしている other_user が自分自身ではないかを検証
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  # フォローがあればフォローを外す
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  # フォローしている User 達を取得しother_user が含まれていないかを確認
  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    @new_posts = Post.limit(10).order(" created_at DESC ")
    @all_user = User.all
    if user_signed_in?
      @posts = current_user.posts.includes(:user).order(id: "DESC")
    else
      @posts = Post.includes(:user)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  #ガード節
  # def not_edit_user
  #   if @post.user_id != current_user.id 
  #     flash[:alert] = "該当ユーザーではありません"
  #     redirect_to root_path
  #   end 
  # end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: :index

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を編集しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end
  end

  def favorites
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
    @posts = @user.posts
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    @posts = @user.posts
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :password, :password_confirmation)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HobbyBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_header.html.haml
.main-header
  .title
    = link_to "RECORD@job", root_path, class: "title"
  -# .search
  -#   = form_with(url:'#', method: :get, local: true, class: "search__form") do |f|
  -#     = f.text_field :keyword,class:'search-field',placeholder: '検索'#,value: @keyword
  -#     = icon('fas', 'search', class: 'search-icon')
  -# .table-content
  -#   .header-article
  -#     新着記事
  -#   .header-rank
  -#     人気の記事
  - if user_signed_in?
    .register
      .new-post
        = link_to "新規投稿", new_post_path, class: "new-post"
      .user-name
        = link_to current_user.nickname, user_path(current_user), class: "user-name"
      .log-out
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "log-out"
      .profile-edit
        = link_to "プロフィール編集", edit_user_path(current_user.id), class: "profile-edit"
      -if current_user.image.present?
        .profile-photo
          = image_tag current_user.image.to_s, size: "60x60", class: 'profile-photo'
      -else
        .profile-photo
          = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "60x60", class: 'mypage__icon'
  - else
    .register
      .new-register
        = link_to "新規登録", new_user_registration_path, class: "new-register"
      .log-in
        = link_to "ログイン", new_user_session_path, class: "log-in"
      
      

app/views/posts/edit.html.haml
=render 'posts/header'
.post-container
  .post-content
    .post-content__top
      新規記事の作成
    .post-content__main
      = form_with model: @post, class: :form, local: true do |f|
        .post-content__main__form
          .post-content__main__form__title
            = f.text_field :title, placeholder: "タイトル", class: "post__form__title"
          .post-content__main__form__text
            = f.text_area :content, placeholder: "ブログ本文", class: "post__form__text"
          .post-content__main__form__btn
            = f.submit '投稿する', class: "post__form__btn"

app/views/posts/index.html.haml
=render 'posts/header'

.main-container
  .slick-content
    .article-rank
      .rank-title
        人気の記事
      %ul.contents
        %li.contents__left
          日付
        %li.contents__center
          タイトル
        %li.contents__right
          ニックネーム
      - @all_ranks.each do |post|
        %ul.postlist
          %li.date
            = post.created_at.strftime('%-m/%-d')
          %li.post
            = link_to post.title, post_path(post.id), class: "post--title"
          %li.nickname
            = link_to post.user.nickname, user_path(post.user), class: "nickname--user"
    .article-new
      .new-title
        新着記事
      %ul.contents
        %li.contents__left
          日付
        %li.contents__center
          タイトル
        %li.contents__right
          ニックネーム
      - @new_posts.each do |post|
        %ul.postlist
          %li.date
            = post.created_at.strftime('%-m/%-d')
          %li.post
            = link_to post.title, post_path(post.id), class: "post--title"
          %li.nickname
            = link_to post.user.nickname, user_path(post.user), class: "nickname--user"
  .right-content
    - if user_signed_in?
      .right-content__signed-in
        .mypage
          = link_to "マイページ", user_path(current_user), class: "mypage--link"
        %ul.contents
          %li.contents__left
            日付
          %li.contents__center
            タイトル
          %li.contents__right
            ニックネーム
        - @posts.each do |post|
          %ul.postlist
            %li.date
              = post.created_at.strftime('%-m/%-d')
            %li.post
              = link_to post.title, post_path(post.id), class: "post--title"
            %li.nickname
              = link_to post.user.nickname, user_path(post.user), class: "nickname--user"
    - else
      .right-content__signed-out
        .advertising
          ユーザー紹介
        .user-list
          - @all_user.each do |user|
            .user-line
              .introduction-photo
                -if user.image.present?
                  = image_tag user.image.to_s, size: "50x50", class: 'mypage__icon'
                - else
                  = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "50x50", class: 'mypage__icon'
              .introduction-nickname
                = link_to user.nickname, user_path(user), class: "introduction-nickname--title"

app/views/posts/new.html.haml
=render 'posts/header'
.post-container
  .post-content
    .post-content__top
      新規記事の作成
    .post-content__main
      = form_with model: @post, class: :form, local: true do |f|
        .post-content__main__form
          .post-content__main__form__title
            = f.text_field :title, placeholder: "タイトル", class: "post__form__title"
          .post-content__main__form__text
            = f.text_area :content, placeholder: "ブログ本文", class: "post__form__text"
          .post-content__main__form__btn
            = f.submit '投稿する', class: "post__form__btn"

app/views/posts/show.html.haml
=render 'posts/header'

.details-container
  .details-content
    .details-content__title
      = @post.title 
    .details-content__time
      = @post.created_at
    .details-content__edit
      - if user_signed_in? && current_user.id == @post.user_id
        = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
        = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"
    .details-content__text
      = simple_format @post.content
    .details-content__like
      .details-content__like__count
        いいね件数:
        = @post.likes.count
      .details-content__like__bottun
        - if current_user.already_liked?(@post)
          .details-content__like__delite
            = button_to 'いいねを取り消す', post_like_path(@post), method: :delete
        -else
          .details-content__like__addition
            = button_to 'いいね', post_likes_path(@post)
      .details-content__like__user
        いいねしたユーザー:
      .details-content__like__user-name
        - @post.liked_users.each do |user|
          = link_to user.nickname, user_path(user), class: "user-nickname"
    .details-content__comment
      .details-content__comment__list
        - @comments.each do |comment|
          .commentlist
            .comment-photo
              -if comment.user.image.present?
                = image_tag comment.user.image.to_s, size: "60x60"
              - else
                = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "60x60"
            .comment-nickname
              = link_to comment.user.nickname, user_path(comment.user), class: "comment-nickname--title"
            .comment-text
              = comment.text
      .details-content__comment__practice
        .details-content__comment__practice__photo
          -if current_user.image.present?
            = image_tag current_user.image.to_s, size: "60x60", class: 'mypage__icon'
          - else
            = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "60x60", class: 'mypage__icon'
        .details-content__comment__practice__text
          = form_with(model: [@post, @comment], local: true) do |f|
            = f.text_area :text, placeholder: "コメントを入力...", class: "details-content__comment__practice__text__form"
            = f.submit "投稿する" 

app/views/relationships/_follow_button.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー中', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー', class: 'follows'

app/views/users/edit.html.haml
=render 'posts/header'

.profile-container
  .profile-container__top
    プロフィールの編集
  .profile-container__edit
    = form_with model: @user,  local: true do |f|
      .profile-container__edit__image
        = f.label :image, class: "image-label" do
          プロフィール画像をアップロード
        = f.file_field :image ,class: 'file'
      .profile-container__edit__nickname
        = f.text_field :nickname, class: 'edit',value: @user.nickname
      .profile-container__edit__email
        = f.email_field :email, class: 'edit'
      .profile-container__edit__password
        = f.password_field :password, class: 'edit', placeholder: "新しいパスワード"
      .profile-container__edit__password-confirmation
        = f.password_field :password_confirmation, class: 'edit', placeholder: "新しいパスワード確認"
      .profile-container__edit__bottom
        = f.submit '変更する', class: 'edit-send'

app/views/users/favorites.html.haml
=render 'posts/header'

.user-details-container
  .user-details-content
    .user-details-content__profile
      -if @user.image.present?
        .user-details-content__profile__image
          = image_tag @user.image.to_s, size: "150x150", class: 'mypage__icon'
      - else
        .user-details-content__profile__image
          = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "150x150", class: 'mypage__icon'
      .user-details-content__profile__name
        = @user.nickname
      .user-deteils-content__profile__follow
        = render 'relationships/follow_button', user: @user
    .user-details-content__right
      .user-details-content__right__top
        .user-details-content__right__top__post
          = link_to user_path(@user), class: 'btn btn-default' do
            %h1 投稿
        .user-details-content__right__top__like-main
          = link_to favorites_user_path, class: 'btn btn-default' do
            %h1 いいねした投稿
        .user-details-content__right__top__following
          = link_to followings_user_path, class: 'btn btn-default' do
            %h1 フォロー
        .user-details-content__right__top__followers
          = link_to followers_user_path, class: 'btn btn-default' do
            %h1 フォロワー
      .user-details-content__right__content
        .user-details-content__right__content__top
          %h3 いいねした投稿
        .user-details-content__right__content__center
          - @user.liked_posts.each do |post|
            .show-postlist
              .showside-photo
                -if post.user.image.present?
                  = image_tag post.user.image.to_s, size: "100x100", class: 'mypage__icon'
                - else
                  = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "100x100", class: 'mypage__icon'
                .showside-nickname
                  = link_to post.user.nickname, user_path(post.user), class: "showside-nickname--title"
              .showpost
                = link_to post.title, post_path(post.id), class: "showpost--title"
              .showlike
                .showlike__count
                  いいね件数:
                  = post.likes.count
                .showlike__form
                  - if current_user.already_liked?(post)
                    .showlike__form__delite
                      = button_to 'いいねを取り消す', post_like_path(post), method: :delete
                  -else
                    .showlike__form__addition
                      = button_to 'いいね', post_likes_path(post)

app/views/users/followers.html.haml
=render 'posts/header'

.user-details-container
  .user-details-content
    .user-details-content__profile
      -if @user.image.present?
        .user-details-content__profile__image
          = image_tag @user.image.to_s, size: "150x150", class: 'mypage__icon'
      - else
        .user-details-content__profile__image
          = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "150x150", class: 'mypage__icon'
      .user-details-content__profile__name
        = @user.nickname
      .user-deteils-content__profile__follow
        = render 'relationships/follow_button', user: @user
    .user-details-content__right
      .user-details-content__right__top
        .user-details-content__right__top__post
          = link_to user_path(@user), class: 'btn btn-default' do
            %h1 投稿
        .user-details-content__right__top__like
          = link_to favorites_user_path, class: 'btn btn-default' do
            %h1 いいねした投稿
        .user-details-content__right__top__following
          = link_to followings_user_path, class: 'btn btn-default' do
            %h1 フォロー
        .user-details-content__right__top__followers-main
          = link_to followers_user_path, class: 'btn btn-default' do
            %h1 フォロワー
      .user-details-content__right__content
        .user-details-content__right__content__top
          %h3 フォローされているユーザー
        .user-details-content__right__content__center
          - @user.followers.each do |user|
            .show-follow
              .follow-photo
                -if user.image.present?
                  = image_tag user.image.to_s, size: "120x120", class: 'mypage__icon'
                - else
                  = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "120x120", class: 'mypage__icon'
              .follow-nickname
                = link_to user.nickname, user_path(user), class: "follow-nickname--title"
              .follow-button
                = render 'relationships/follow_button', user: user

app/views/users/followings.html.haml
=render 'posts/header'

.user-details-container
  .user-details-content
    .user-details-content__profile
      -if @user.image.present?
        .user-details-content__profile__image
          = image_tag @user.image.to_s, size: "150x150", class: 'mypage__icon'
      - else
        .user-details-content__profile__image
          = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "150x150", class: 'mypage__icon'
      .user-details-content__profile__name
        = @user.nickname
      .user-deteils-content__profile__follow
        = render 'relationships/follow_button', user: @user
    .user-details-content__right
      .user-details-content__right__top
        .user-details-content__right__top__post
          = link_to user_path(@user), class: 'btn btn-default' do
            %h1 投稿
        .user-details-content__right__top__like
          = link_to favorites_user_path, class: 'btn btn-default' do
            %h1 いいねした投稿
        .user-details-content__right__top__following-main
          = link_to followings_user_path, class: 'btn btn-default' do
            %h1 フォロー
        .user-details-content__right__top__followers
          = link_to followers_user_path, class: 'btn btn-default' do
            %h1 フォロワー
      .user-details-content__right__content
        .user-details-content__right__content__top
          %h3 フォローしたユーザー
        .user-details-content__right__content__center
          - @user.followings.each do |user|
            .show-follow
              .follow-photo
                -if user.image.present?
                  = image_tag user.image.to_s, size: "120x120", class: 'mypage__icon'
                - else
                  = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "120x120", class: 'mypage__icon'
              .follow-nickname
                = link_to user.nickname, user_path(user), class: "follow-nickname--title"
              .follow-button
                = render 'relationships/follow_button', user: user

app/views/users/show.html.haml
=render 'posts/header'

.user-details-container
  .user-details-content
    .user-details-content__profile
      -if @user.image.present?
        .user-details-content__profile__image
          = image_tag @user.image.to_s, size: "150x150", class: 'mypage__icon'
      - else
        .user-details-content__profile__image
          = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "150x150", class: 'mypage__icon'
      .user-details-content__profile__name
        = @user.nickname
      .user-details-content__profile__follow
        = render 'relationships/follow_button', user: @user
      -# .user-details-content__profile__follow-count
      -#   .followings
      -#     = @user.followings.count
      -#     フォロー
      -#   .followers
      -#     = @user.followers.count
      -#     フォロワー
    .user-details-content__right
      .user-details-content__right__top
        .user-details-content__right__top__post-main
          = link_to user_path(@user), class: 'btn btn-default' do
            %h1 投稿
            -# .title
            -#   投稿
            -# .count
            -#   = @user.posts.count
        .user-details-content__right__top__like
          = link_to favorites_user_path, class: 'btn btn-default' do
            %h1 いいねした投稿
        .user-details-content__right__top__following
          = link_to followings_user_path, class: 'btn btn-default' do
            %h1 フォロー
        .user-details-content__right__top__followers
          = link_to followers_user_path, class: 'btn btn-default' do
            %h1 フォロワー
      .user-details-content__right__content
        .user-details-content__right__content__top
          %h3 投稿
        .user-details-content__right__content__center
          - @posts.each do |post|
            .show-postlist
              .showside-photo
                -if @user.image.present?
                  = image_tag @user.image.to_s, size: "120x120", class: 'mypage__icon'
                - else
                  = image_tag "/images/noimage.jpeg", alt: "プロフィール画像",size: "120x120", class: 'mypage__icon'
              .showpost
                = link_to post.title, post_path(post.id), class: "showpost--title"
              .showlike
                .showlike__count
                  いいね件数:
                  = post.likes.count
                .showlike__form
                  - if current_user.already_liked?(post)
                    .showlike__form__delite
                      = button_to 'いいねを取り消す', post_like_path(post), method: :delete
                  -else
                    .showlike__form__addition
                      = button_to 'いいね', post_likes_path(post)